(() => {
  const BPM = 90, BEAT_MS = 60000 / BPM, SIZE = 8;
  const PIECES = { king:'♚', queen:'♛', rook:'♜', bishop:'♝', knight:'♞', pawn:'♟' };
  const NAMES = { king:'King', queen:'Queen', rook:'Rook', bishop:'Bishop', knight:'Knight', pawn:'Pawn' };
  const VALUES = { pawn:1, knight:3, bishop:3, rook:5, queen:9, king:4 };
  const DIRECTIONS = { N:[-1,0], NE:[-1,1], E:[0,1], SE:[1,1], S:[1,0], SW:[1,-1], W:[0,-1], NW:[-1,-1] };
  const KNIGHT = { N:[-2,1], NE:[-1,2], E:[1,2], SE:[2,1], S:[2,-1], SW:[1,-2], W:[-1,-2], NW:[-2,-1] };
  const NUMPAD_BY_DIRECTION = { SW:'1', S:'2', SE:'3', W:'4', E:'6', NW:'7', N:'8', NE:'9' };
  const NOTES = [
    { name:'C4', hz:261.63, dir:'N', arrow:'↑' }, { name:'D4', hz:293.66, dir:'NE', arrow:'↗' },
    { name:'E4', hz:329.63, dir:'E', arrow:'→' }, { name:'G4', hz:392, dir:'SE', arrow:'↘' },
    { name:'A4', hz:440, dir:'S', arrow:'↓' }, { name:'C5', hz:523.25, dir:'SW', arrow:'↙' },
    { name:'D5', hz:587.33, dir:'W', arrow:'←' }, { name:'E5', hz:659.25, dir:'NW', arrow:'↖' }
  ];
  const sliderTypes = new Set(['rook','bishop','queen']);
  const boardEl = document.querySelector('#board'), sequencerEl = document.querySelector('#sequencer'), padsEl = document.querySelector('#notePads');
  const logEl = document.querySelector('#log'), playButton = document.querySelector('#playButton'), replayButton = document.querySelector('#replayButton');
  const el = id => document.getElementById(id);
  let audio, timer, state, forecasts={byPiece:new Map(),byKey:new Map()};

  const mulberry32 = seed => () => { let t = seed += 0x6D2B79F5; t = Math.imul(t ^ t >>> 15, t | 1); t ^= t + Math.imul(t ^ t >>> 7, t | 61); return ((t ^ t >>> 14) >>> 0) / 4294967296; };
  const shuffled = (items, random) => items.map(value => ({value, sort:random()})).sort((a,b) => a.sort-b.sort).map(item => item.value);
  const clonePhrase = phrase => [...phrase];
  const cloneStacks = stacks => stacks.map(stack => stack.map(event => ({...event})));
  const note = index => NOTES[index];
  const makeState = seed => {
    const random = mulberry32(seed), cells = shuffled([...Array(64).keys()], random), roster = ['king','queen','rook','bishop','knight','pawn'];
    const pieces = [];
    ['white','black'].forEach((color, side) => roster.forEach((type, order) => {
      const cell = cells[side * roster.length + order];
      pieces.push({id:`${color}-${type}-${order}`, color, type, row:Math.floor(cell/SIZE), col:cell%SIZE});
    }));
    return { seed, pieces, queues:{ white:shuffled(pieces.filter(p=>p.color==='white').map(p=>p.id),random), black:shuffled(pieces.filter(p=>p.color==='black').map(p=>p.id),random) }, cursors:{white:0,black:0}, sharedNextColor:'black', loop:0, beat:0,
      phrase:Array(8).fill(null), queuedPhrase:Array(8).fill(null), blackPhrase:Array(8).fill(null), blackQueuedPhrase:Array(8).fill(null), sharedPhrase:Array.from({length:8},()=>[]), sharedQueuedPhrase:Array.from({length:8},()=>[]), history:[], phase:'editing', selectedBeat:0, additionsThisLoop:0, editAction:null, continuous:false, eitherSide:true, crossDelete:true, captured:[], logs:['Board randomized. Add one white note to begin your first loop.'], replayIndex:0 };
  };
  const pieceById = id => state.pieces.find(piece => piece.id === id);
  const currentPiece = color => { const queue = state.queues[color]; if (!queue.length) return null; state.cursors[color] %= queue.length; return pieceById(queue[state.cursors[color]]); };
  const sharedColorAt = offset => (offset % 2 === 0) === (state.sharedNextColor === 'black') ? 'black' : 'white';
  const currentSharedPiece = offset => { const color=sharedColorAt(offset), queue=state.queues[color]; if(!queue.length) return null; return pieceById(queue[state.cursors[color] % queue.length]); };
  const inside = (row,col) => row>=0 && row<SIZE && col>=0 && col<SIZE;
  const at = (row,col) => state.pieces.find(piece => piece.row===row && piece.col===col);
  const addLog = message => { state.logs.unshift(message); state.logs = state.logs.slice(0,18); };
  const advance = color => { const queue = state.queues[color]; if (queue.length) state.cursors[color] = (state.cursors[color]+1) % queue.length; };
  const advanceShared = () => { const color=state.sharedNextColor; advance(color); state.sharedNextColor=color==='black'?'white':'black'; };
  const removePiece = victim => { state.pieces = state.pieces.filter(piece => piece.id !== victim.id); const queue = state.queues[victim.color], index = queue.indexOf(victim.id); if (index !== -1) { queue.splice(index,1); if (index < state.cursors[victim.color]) state.cursors[victim.color]--; if (state.cursors[victim.color] < 0) state.cursors[victim.color] = 0; } state.captured.push(victim); };
  const finishIfNeeded = () => { const colors = new Set(state.pieces.map(piece => piece.color)); if (colors.size < 2) { state.phase='ended'; clearTimeout(timer); const winner = colors.size ? [...colors][0] : 'Nobody'; addLog(`${winner} wins — every opposing piece was captured.`); replayButton.disabled = !state.history.length; return true; } return false; };
  const moveTo = (piece,row,col) => { const target=at(row,col); if (target?.color===piece.color) return false; if (target) { removePiece(target); addLog(`${NAMES[piece.type]} captures ${NAMES[target.type]}.`); } piece.row=row; piece.col=col; if (piece.type==='pawn' && (row===0 || row===7)) { piece.type='queen'; addLog('A pawn is promoted to queen.'); } return true; };
  const sliderDirectionAllowed = (type,dir) => type==='queen' || (type==='rook' && ['N','E','S','W'].includes(dir)) || (type==='bishop' && !['N','E','S','W'].includes(dir));
  const previewMove = (piece,dir) => {
    if (sliderTypes.has(piece.type)) {
      if (!sliderDirectionAllowed(piece.type,dir)) return null;
      const [dr,dc]=DIRECTIONS[dir]; let destination=null, capture=null;
      for (let step=1; step<=SIZE; step++) { const row=piece.row+dr*step, col=piece.col+dc*step; if (!inside(row,col)) break; const target=at(row,col); if (target?.color===piece.color) break; destination={row,col}; if (target) { capture=target; break; } }
      return destination && {...destination,capture};
    }
    if (piece.type==='pawn') {
      const forward=piece.color==='white' ? -1 : 1, diagonals=piece.color==='white' ? ['NW','NE'] : ['SW','SE'], forwardDir=forward<0 ? 'N':'S';
      const [dr,dc]=DIRECTIONS[dir], row=piece.row+dr, col=piece.col+dc;
      if (dir===forwardDir && inside(row,col) && !at(row,col)) return {row,col,capture:null};
      const diagonalTarget=at(row,col); if (diagonals.includes(dir) && inside(row,col) && diagonalTarget && diagonalTarget.color!==piece.color) return {row,col,capture:diagonalTarget};
      const fallbackRow=piece.row+forward; return inside(fallbackRow,piece.col) && !at(fallbackRow,piece.col) ? {row:fallbackRow,col:piece.col,capture:null} : null;
    }
    const [dr,dc]=piece.type==='knight' ? KNIGHT[dir] : DIRECTIONS[dir], row=piece.row+dr, col=piece.col+dc;
    if (!inside(row,col) || at(row,col)?.color===piece.color) return null;
    return {row,col,capture:at(row,col) || null};
  };
  const resolveCommand = (piece,dir) => {
    const move=previewMove(piece,dir);
    if (!move) { addLog(`${NAMES[piece.type]} drops an invalid command.`); return; }
    moveTo(piece,move.row,move.col);
    addLog(`${NAMES[piece.type]} moves ${dir}${sliderTypes.has(piece.type) ? ' to its furthest open square' : ''}.`);
  };
  const nearestEnemyDistance = piece => Math.min(...state.pieces.filter(other=>other.color!==piece.color).map(other=>Math.abs(piece.row-other.row)+Math.abs(piece.col-other.col)));
  const chooseBlackNote = () => {
    const piece=state.eitherSide ? currentSharedPiece(0) : currentPiece('black'); if (!piece) return 0;
    const before=nearestEnemyDistance(piece);
    const options=NOTES.map((item,index) => ({index,move:previewMove(piece,item.dir)})).filter(option=>option.move);
    if (!options.length) return Math.floor(Math.random()*NOTES.length);
    const scored=options.map(option => { const captured=option.move.capture; const after=Math.min(...state.pieces.filter(other=>other.color==='white').map(other=>Math.abs(option.move.row-other.row)+Math.abs(option.move.col-other.col))); return {...option, score:(captured ? 100+VALUES[captured.type]*10 : 0)+(before-after)*3+Math.random()}; });
    return scored.sort((a,b)=>b.score-a.score)[0].index;
  };
  const queueBlackNote = () => {
    const deleteChance = .28;
    if (state.eitherSide) {
      const whiteNotes=[]; state.sharedQueuedPhrase.forEach((stack,beat)=>stack.forEach((event,index)=>{ if(event.source==='white') whiteNotes.push({stack,index,beat}); }));
      if (whiteNotes.length && Math.random()<deleteChance) { const target=whiteNotes[Math.floor(Math.random()*whiteNotes.length)]; target.stack.splice(target.index,1); addLog(`Black AI deletes a white note from beat ${target.beat+1}.`); return; }
      const beat=Math.floor(Math.random()*8), index=chooseBlackNote();
      state.sharedQueuedPhrase[beat].push({source:'black',index});
      addLog(`Black AI stacks ${note(index).name} on beat ${beat+1}.`);
      return;
    }
    const whiteBeats=state.queuedPhrase.map((entry,beat)=>entry===null?null:beat).filter(beat=>beat!==null);
    if (whiteBeats.length && Math.random()<deleteChance) { const beat=whiteBeats[Math.floor(Math.random()*whiteBeats.length)]; state.queuedPhrase[beat]=null; addLog(`Black AI deletes a white note from beat ${beat+1}.`); return; }
    const openBeats = state.blackQueuedPhrase.map((entry,index) => entry === null ? index : null).filter(index => index !== null);
    if (!openBeats.length) return;
    const beat = openBeats[Math.floor(Math.random() * openBeats.length)], index = chooseBlackNote();
    state.blackQueuedPhrase[beat] = index;
    addLog(`Black AI queues ${note(index).name} for black beat ${beat + 1}.`);
  };
  const playChord = indexes => { if (!audio || !indexes.length) return; const now=audio.currentTime; indexes.filter(index=>index!==null).forEach((index,i) => { const osc=audio.createOscillator(), gain=audio.createGain(); osc.type=i ? 'triangle':'sine'; osc.frequency.value=note(index).hz; gain.gain.setValueAtTime(.0001,now); gain.gain.exponentialRampToValueAtTime(.06,now+.015); gain.gain.exponentialRampToValueAtTime(.0001,now+.42); osc.connect(gain).connect(audio.destination); osc.start(now); osc.stop(now+.45); }); };
  const ensureAudio = () => { if (!audio) audio=new (window.AudioContext||window.webkitAudioContext)(); if (audio.state==='suspended') audio.resume(); };
  const executeSharedStack = (events,record) => {
    playChord(events.map(event=>event.index));
    for (const event of events) { const piece=currentSharedPiece(0); if (!piece) break; resolveCommand(piece,note(event.index).dir); advanceShared(); if (finishIfNeeded()) break; }
    if (record) state.history.push({shared:true,events:events.map(event=>({...event}))});
  };
  const executeBeat = (whiteNote,blackNote,record) => {
    playChord([whiteNote,blackNote]);
    if (state.eitherSide) {
      for (const noteIndex of [whiteNote,blackNote]) { if (noteIndex===null) continue; const piece=currentSharedPiece(0); if (!piece) break; resolveCommand(piece,note(noteIndex).dir); advanceShared(); if (finishIfNeeded()) { if (record) state.history.push({white:whiteNote,black:blackNote}); return; } }
      if (record) state.history.push({white:whiteNote,black:blackNote});
      return;
    }
    const white=currentPiece('white'); if (white && whiteNote!==null) { resolveCommand(white,note(whiteNote).dir); advance('white'); if (finishIfNeeded()) { if (record) state.history.push({white:whiteNote,black:blackNote}); return; } }
    const black=currentPiece('black'); if (black && blackNote!==null) { resolveCommand(black,note(blackNote).dir); advance('black'); finishIfNeeded(); }
    if (record) state.history.push({white:whiteNote,black:blackNote});
  };
  const tickLoop = () => {
    if (state.phase!=='playing') return;
    if (state.eitherSide) executeSharedStack(state.sharedPhrase[state.beat],true); else { const whiteNote=state.phrase[state.beat], blackNote=state.blackPhrase[state.beat]; executeBeat(whiteNote,blackNote,true); } state.beat++;
    if (state.phase==='ended') { render(); return; }
    if (state.beat>=8) { state.loop++; state.beat=0; if (state.eitherSide) { state.sharedPhrase=cloneStacks(state.sharedQueuedPhrase); state.sharedQueuedPhrase=cloneStacks(state.sharedPhrase); } else { state.phrase=clonePhrase(state.queuedPhrase); state.blackPhrase=clonePhrase(state.blackQueuedPhrase); state.queuedPhrase=clonePhrase(state.phrase); state.blackQueuedPhrase=clonePhrase(state.blackPhrase); } queueBlackNote(); state.additionsThisLoop=0; state.editAction=null; if (!state.continuous) { state.phase='editing'; addLog(`Loop ${state.loop} complete. Add one note, then continue.`); render(); return; } addLog(`Loop ${state.loop} begins with your queued phrase.`); render(); timer=setTimeout(tickLoop,BEAT_MS); return; }
    render(); timer=setTimeout(tickLoop,BEAT_MS);
  };
  const startLoop = () => { ensureAudio(); if (state.phase==='editing') { if (state.eitherSide) { if (!state.sharedQueuedPhrase.some(stack=>stack.some(event=>event.source==='black'))) queueBlackNote(); state.sharedPhrase=cloneStacks(state.sharedQueuedPhrase); state.sharedQueuedPhrase=cloneStacks(state.sharedPhrase); } else { if (!state.blackQueuedPhrase.some(entry => entry !== null)) queueBlackNote(); state.phrase=clonePhrase(state.queuedPhrase); state.blackPhrase=clonePhrase(state.blackQueuedPhrase); state.queuedPhrase=clonePhrase(state.phrase); state.blackQueuedPhrase=clonePhrase(state.blackPhrase); } state.additionsThisLoop=0; state.editAction=null; } state.phase='playing'; state.beat=0; tickLoop(); };
  const startReplay = () => { if (!state.history.length) return; ensureAudio(); clearTimeout(timer); const history=state.history.map(event=>event.shared?{shared:true,events:event.events.map(item=>({...item}))}:{...event}), shared=history.some(event=>event.shared); state=makeState(state.seed); state.eitherSide=shared; state.phase='replaying'; state.history=history; state.replayIndex=0; addLog('Replaying the recorded performance.'); const tick=()=> { if (state.phase!=='replaying') return; if (state.replayIndex>=history.length) { state.phase='ended'; addLog('Replay complete.'); render(); return; } const event=history[state.replayIndex]; if(event.shared) executeSharedStack(event.events,false); else executeBeat(event.white,event.black,false); state.beat=state.replayIndex%8; state.replayIndex++; render(); timer=setTimeout(tick,BEAT_MS); }; tick(); };
  const canEdit = () => state.phase==='editing' || (state.phase==='playing' && state.continuous);
  const addNote = index => { if (!canEdit() || state.editAction) { addLog('This loop already has an editing action.'); } else if (state.eitherSide) { state.sharedQueuedPhrase[state.selectedBeat].push({source:'white',index}); state.additionsThisLoop++; state.editAction='add'; addLog(`${note(index).name} stacked on beat ${state.selectedBeat+1}.`); } else if (state.queuedPhrase[state.selectedBeat]!==null) { addLog(`Beat ${state.selectedBeat+1} already has a white note.`); } else { state.queuedPhrase[state.selectedBeat]=index; state.additionsThisLoop++; state.editAction='add'; addLog(`${note(index).name} queued for white beat ${state.selectedBeat+1}.`); } render(); };
  const deleteNote = (remove,source) => { if(!canEdit() || state.editAction) { addLog('This loop already has an editing action.'); render(); return; } if(source==='black' && !state.crossDelete) { addLog('Enable Cross-side deletions to remove black notes.'); render(); return; } remove(); state.editAction='delete'; state.additionsThisLoop=1; addLog(`Deleted a ${source} note.`); render(); };
  const upcomingTurnNumbers = () => { const numbers=new Map(); let number=1; const record=(id,imminent)=>{ if(!pieceById(id)) return; const entry=numbers.get(id) || {imminent:[],later:null}; if(imminent) entry.imminent.push(number); else if(entry.later===null) entry.later=number; numbers.set(id,entry); number++; }; if(state.eitherSide) { const source=state.phase==='editing'?state.sharedQueuedPhrase:state.sharedPhrase, cursors={...state.cursors}; let color=state.sharedNextColor; for(let offset=0;offset<128;offset++) { for(const event of source[(state.beat+offset)%8]) { const queue=state.queues[color]; if(queue.length) { const id=queue[cursors[color]%queue.length]; record(id,offset<8); cursors[color]=(cursors[color]+1)%queue.length; } color=color==='black'?'white':'black'; } } return numbers; } const source=state.phase==='editing' ? {white:state.queuedPhrase,black:state.blackQueuedPhrase} : {white:state.phrase,black:state.blackPhrase}; const cursors={...state.cursors}; for(let offset=0;offset<128;offset++) { const beat=(state.beat+offset)%8; for(const color of ['white','black']) { if(source[color][beat]===null) continue; const queue=state.queues[color]; if(!queue.length) continue; const id=queue[cursors[color]%queue.length]; record(id,offset<8); cursors[color]=(cursors[color]+1)%queue.length; } } return numbers; };
  const buildForecasts = () => { const byPiece=new Map(), byKey=new Map(), add=(piece,noteIndex,key)=>{ if(!piece) return; const forecast={piece,noteIndex,key,move:previewMove(piece,note(noteIndex).dir)}; byKey.set(key,forecast); const list=byPiece.get(piece.id)||[]; list.push(forecast); byPiece.set(piece.id,list); }; if(state.eitherSide) { const source=state.phase==='editing'?state.sharedQueuedPhrase:state.sharedPhrase, cursors={...state.cursors}; let color=state.sharedNextColor; for(let offset=0;offset<8;offset++) { const beat=(state.beat+offset)%8; source[beat].forEach((event,index)=>{ const queue=state.queues[color], piece=queue.length?pieceById(queue[cursors[color]%queue.length]):null; add(piece,event.index,`shared-${beat}-${index}`); if(queue.length) cursors[color]=(cursors[color]+1)%queue.length; color=color==='black'?'white':'black'; }); } } else { const source=state.phase==='editing'?{white:state.queuedPhrase,black:state.blackQueuedPhrase}:{white:state.phrase,black:state.blackPhrase}, cursors={...state.cursors}; for(let offset=0;offset<8;offset++) { const beat=(state.beat+offset)%8; for(const color of ['white','black']) { const noteIndex=source[color][beat], queue=state.queues[color]; if(noteIndex===null||!queue.length) continue; const piece=pieceById(queue[cursors[color]%queue.length]); add(piece,noteIndex,`${color}-${beat}`); cursors[color]=(cursors[color]+1)%queue.length; } } } return {byPiece,byKey}; };
  const setForecastFocus = key => { document.querySelectorAll('.forecast-focus').forEach(node=>node.classList.remove('forecast-focus')); const normalKnight=state.eitherSide?currentSharedPiece(0):currentPiece('white'); if(!key) { showKnightOverlay(normalKnight?.type==='knight'?normalKnight:null); return; } const seed=forecasts.byKey.get(key), related=seed ? forecasts.byPiece.get(seed.piece.id) : []; if(!related?.length) return; document.querySelector(`[data-piece-id="${seed.piece.id}"]`)?.classList.add('forecast-focus'); related.forEach(forecast=>document.querySelectorAll(`[data-action-key="${forecast.key}"]`).forEach(node=>node.classList.add('forecast-focus'))); showKnightOverlay(seed.piece.type==='knight'?seed.piece:null); };
  const bindForecast = (element,key) => { element.dataset.actionKey=key; element.onpointerenter=()=>setForecastFocus(key); element.onpointerleave=()=>setForecastFocus(null); };
  const knightMoveSvg = dir => { const [dr,dc]=KNIGHT[dir], endY=12+dr*4, endX=12+dc*4; return `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 12 V${endY} H${endX}"/><circle cx="${endX}" cy="${endY}" r="2"/></svg>`; };
  const showKnightOverlay = piece => { document.querySelectorAll('.knight-key').forEach(node=>node.remove()); if(!piece||piece.type!=='knight') return; Object.entries(KNIGHT).forEach(([dir,[dr,dc]])=>{ const row=piece.row+dr,col=piece.col+dc; if(!inside(row,col)) return; const target=document.querySelector(`[data-board-row="${row}"][data-board-col="${col}"]`), key=document.createElement('span'); if(!target) return; key.className=`knight-key ${previewMove(piece,dir)?'':'invalid'}`; key.textContent=NUMPAD_BY_DIRECTION[dir]; target.append(key); }); };
  const renderBoard = () => { boardEl.innerHTML=''; forecasts=buildForecasts(); const whiteActive=state.eitherSide?currentSharedPiece(0):currentPiece('white'), blackActive=state.eitherSide?currentSharedPiece(1):currentPiece('black'), turns=upcomingTurnNumbers(); for (let row=0;row<SIZE;row++) for (let col=0;col<SIZE;col++) { const square=document.createElement('div'); square.className=`square ${(row+col)%2?'dark':'light'}`; square.dataset.boardRow=row; square.dataset.boardCol=col; const piece=at(row,col); if (piece?.id===whiteActive?.id) square.classList.add('active'); if (piece?.id===blackActive?.id) square.classList.add('black-active'); if (piece) { square.dataset.pieceId=piece.id; const icon=document.createElement('span'); icon.className=`piece ${piece.color}`; icon.textContent=PIECES[piece.type]; square.append(icon); const pieceForecasts=forecasts.byPiece.get(piece.id)||[]; pieceForecasts.forEach((forecast,index)=>{ const arrow=document.createElement('span'); arrow.className=`move-arrow ${piece.type==='knight'?'knight-move':''} ${forecast.move?'':'invalid'}`; arrow.style.right=`${4+index*21}px`; if(piece.type==='knight') arrow.innerHTML=knightMoveSvg(note(forecast.noteIndex).dir); else arrow.textContent=note(forecast.noteIndex).arrow; arrow.title=forecast.move ? `${NAMES[piece.type]} will move ${note(forecast.noteIndex).dir}` : `${NAMES[piece.type]} will drop this command`; square.append(arrow); }); if(pieceForecasts.length) bindForecast(square,pieceForecasts[0].key); const turn=turns.get(piece.id); if(turn) { const badge=document.createElement('span'); badge.className=`turn-number ${piece.color} ${turn.imminent.length?'':'dimmed'}`; badge.textContent=turn.imminent.length ? turn.imminent.join('·') : turn.later; square.append(badge); } } if (row===7 || col===0) { const coord=document.createElement('small'); coord.className='coord'; coord.textContent=col===0 ? 8-row : 'abcdefgh'[col]; square.append(coord); } boardEl.append(square); } showKnightOverlay(whiteActive?.type==='knight'?whiteActive:null); };
  const renderSequencer = () => { sequencerEl.innerHTML=''; state.queuedPhrase.forEach((entry,beat) => { const column=document.createElement('div'); column.className=`beat ${state.selectedBeat===beat?'selected':''} ${state.phase==='playing' && state.beat===beat?'playing':''}`; column.onclick=()=>{ if(canEdit()) { state.selectedBeat=beat; render(); } }; column.innerHTML=`<div class="beat-label">WHITE · BEAT ${beat+1}</div>`; if (entry===null) { const empty=document.createElement('div'); empty.className='empty-slot'; empty.textContent='—'; column.append(empty); } else { const item=document.createElement('div'); item.className='slot-note'; item.innerHTML=`<span>${note(entry).name} ${note(entry).arrow}</span>`; if (canEdit()) { const remove=document.createElement('button'); remove.textContent='×'; remove.title='Remove white note for next loop'; remove.onclick=event=>{ event.stopPropagation(); state.queuedPhrase[beat]=null; render(); }; item.append(remove); } column.append(item); } sequencerEl.append(column); }); };
  const renderSharedSequencer = () => { sequencerEl.innerHTML=''; state.sharedQueuedPhrase.forEach((stack,beat)=>{ const column=document.createElement('div'); column.className=`beat ${state.selectedBeat===beat?'selected':''} ${state.phase==='playing'&&state.beat===beat?'playing':''}`; column.onclick=()=>{ if(canEdit()) { state.selectedBeat=beat; render(); } }; column.innerHTML=`<div class="beat-label">BEAT ${beat+1}</div>`; if(!stack.length) { const empty=document.createElement('div'); empty.className='empty-slot'; empty.textContent='-'; column.append(empty); } stack.forEach((event,index)=>{ const item=document.createElement('div'); item.className=`slot-note ${event.source==='black'?'black-note':''}`; item.innerHTML=`<span>${event.source==='black'?'B':'W'} ${note(event.index).name} ${note(event.index).arrow}</span>`; bindForecast(item,`shared-${beat}-${index}`); if(canEdit()&&(event.source==='white'||state.crossDelete)) { const remove=document.createElement('button'); remove.textContent='x'; remove.onclick=click=>{ click.stopPropagation(); deleteNote(()=>stack.splice(index,1),event.source); }; item.append(remove); } column.append(item); }); sequencerEl.append(column); }); };
  const appendBlackPreview = () => { state.blackQueuedPhrase.forEach((noteIndex,beat)=>{ if(noteIndex===null) return; const column=sequencerEl.children[beat]; if(!column) return; const item=document.createElement('div'); item.className='slot-note black-note'; item.innerHTML=`<span>B ${note(noteIndex).name} ${note(noteIndex).arrow}</span>`; if(canEdit()&&state.crossDelete) { const remove=document.createElement('button'); remove.textContent='x'; remove.onclick=event=>{ event.stopPropagation(); deleteNote(()=>state.blackQueuedPhrase[beat]=null,'black'); }; item.append(remove); } column.append(item); }); };
  const knightPadHint = dir => { const [dr,dc]=KNIGHT[dir], vertical=`${Math.abs(dr)} ${dr<0?'up':'down'}`, horizontal=`${Math.abs(dc)} ${dc<0?'left':'right'}`; return `${vertical}, ${horizontal}`; };
  const renderPads = () => { el('eitherSideToggle').checked=state.eitherSide; el('eitherSideToggle').disabled=state.phase==='playing'||state.phase==='replaying'||state.phase==='ended'; el('crossDeleteToggle').checked=state.crossDelete; el('crossDeleteToggle').disabled=state.phase==='replaying'||state.phase==='ended'; if(state.eitherSide) renderSharedSequencer(); else { appendBlackPreview(); [...sequencerEl.children].forEach((column,beat)=>{ const remove=column.querySelector('.slot-note:not(.black-note) button'); if(remove) remove.onclick=event=>{ event.stopPropagation(); deleteNote(()=>state.queuedPhrase[beat]=null,'white'); }; }); } const inputPiece=state.eitherSide?currentSharedPiece(0):currentPiece('white'); padsEl.innerHTML=''; NOTES.forEach((item,index)=>{ const pad=document.createElement('button'); pad.className='pad'; pad.disabled=!canEdit() || !!state.editAction; const hint=inputPiece?.type==='knight' ? `${item.dir}: ${knightPadHint(item.dir)}` : item.dir; pad.innerHTML=`<strong>${item.name} ${item.arrow}</strong><small>${hint}</small>`; pad.onclick=()=>addNote(index); padsEl.append(pad); }); };
  const renderUpcoming = () => { const list=el('upcomingPieces'); list.innerHTML=''; const white=currentPiece('white'), black=currentPiece('black'); if (white) { const item=document.createElement('li'); item.className='current'; item.innerHTML=`<span class="queue-piece piece white">${PIECES[white.type]}</span>Next: White ${NAMES[white.type]}`; list.append(item); } const blackEvents=[]; for(let offset=0;offset<16 && blackEvents.length<3;offset++) { const beat=(state.beat+offset)%8, noteIndex=state.blackPhrase[beat]; if(noteIndex!==null) blackEvents.push({beat:beat+1,noteIndex}); } blackEvents.forEach((event,index)=>{ if(!black) return; const piece=pieceById(state.queues.black[(state.cursors.black+index)%state.queues.black.length]); if(!piece) return; const item=document.createElement('li'); item.className=index===0?'black-current':''; item.innerHTML=`<span class="queue-piece piece black">${PIECES[piece.type]}</span>Black ${NAMES[piece.type]}: ${note(event.noteIndex).arrow} B${event.beat}`; list.append(item); }); if(!blackEvents.length) { const item=document.createElement('li'); item.className='black-current'; item.textContent='Black has no queued notes'; list.append(item); } };
  const render = () => { renderBoard(); renderSequencer(); renderPads(); renderUpcoming(); const white=currentPiece('white'), black=currentPiece('black'); el('activePiece').textContent=white ? `Next: White ${NAMES[white.type]} · then Black ${black ? NAMES[black.type] : '—'}` : 'Game complete'; el('loopCount').textContent=state.loop; el('beatStatus').textContent=state.phase==='playing' ? `${state.beat+1} / 8` : state.phase==='replaying' ? `Replay ${state.replayIndex} / ${state.history.length}` : state.phase==='ended' ? 'Ended' : 'Ready — add 1 note'; el('composerHint').textContent=canEdit() ? `${state.continuous&&state.phase==='playing'?'Queued for the next loop.':'Edit the next phrase.'} Beat ${state.selectedBeat+1} selected — ${state.additionsThisLoop?'this loop’s note is queued.':'click a beat, then use numpad 1–4 or 6–9.'}` : state.phase==='replaying' ? 'The recorded phrase is playing without editing pauses.' : 'Start a new board or replay this performance.'; playButton.disabled=state.phase!=='editing'; playButton.textContent=state.loop?'Continue loop':'Start looping'; el('continuousToggle').checked=state.continuous; el('continuousToggle').disabled=state.phase==='replaying'||state.phase==='ended'; replayButton.disabled=!state.history.length||state.phase==='playing'||state.phase==='replaying'; el('whiteCaptured').textContent=state.captured.filter(piece=>piece.color==='white').map(piece=>PIECES[piece.type]).join(' ')||'—'; el('blackCaptured').textContent=state.captured.filter(piece=>piece.color==='black').map(piece=>PIECES[piece.type]).join(' ')||'—'; logEl.innerHTML=state.logs.map(message=>`<li>${message}</li>`).join(''); };
  const setEitherSide = enabled => { state.eitherSide=enabled; if(enabled) { const combine=(white,black)=>white.map((entry,beat)=>[...(entry===null?[]:[{source:'white',index:entry}]),...(black[beat]===null?[]:[{source:'black',index:black[beat]}])]); state.sharedPhrase=combine(state.phrase,state.blackPhrase); state.sharedQueuedPhrase=combine(state.queuedPhrase,state.blackQueuedPhrase); } else { const split=stacks=>({white:stacks.map(stack=>stack.find(event=>event.source==='white')?.index??null),black:stacks.map(stack=>stack.find(event=>event.source==='black')?.index??null)}); const active=split(state.sharedPhrase), queued=split(state.sharedQueuedPhrase); state.phrase=active.white; state.blackPhrase=active.black; state.queuedPhrase=queued.white; state.blackQueuedPhrase=queued.black; } };
  playButton.onclick=startLoop; replayButton.onclick=startReplay; el('continuousToggle').onchange=event=>{ state.continuous=event.target.checked; addLog(state.continuous?'Continuous loop enabled.':'Pause-and-edit mode enabled after this loop.'); render(); }; el('eitherSideToggle').onchange=event=>{ setEitherSide(event.target.checked); addLog(event.target.checked?'Notes now control either side.':'Notes now control their own side.'); render(); }; el('crossDeleteToggle').onchange=event=>{ state.crossDelete=event.target.checked; addLog(state.crossDelete?'Cross-side deletions enabled.':'Cross-side deletions disabled.'); render(); }; el('restartButton').onclick=()=>{ clearTimeout(timer); state=makeState(Math.floor(Math.random()*2**32)); queueBlackNote(); render(); };
  document.addEventListener('keydown',event=>{ const numpad={Numpad1:5,Numpad2:4,Numpad3:3,Numpad4:6,Numpad6:2,Numpad7:7,Numpad8:0,Numpad9:1}; if(Object.hasOwn(numpad,event.code)&&canEdit()) { event.preventDefault(); addNote(numpad[event.code]); } });
  state=makeState(Math.floor(Math.random()*2**32)); queueBlackNote(); render();
})();
